### ISSUE TITLE
can't install for l6

### ISSUE THREAD

**Issue by ITwrx** [mikebronner/laravel-maps#29]
hi,
when trying to install for laravel 6.18.40 i try: `composer require genealabs/laravel-maps:feature/update-to-laravel-6`
but i get:
```
genealabs/laravel-maps dev-feature/update-to-laravel-6 requires illuminate/support 5.5 - 6.0 -> satisfiable by illuminate/support[..., v6.0.4].
...
- don't install illuminate/support v6.0.4|don't install laravel/framework v6.18.40
```
maybe the l6 branch needs an update, or there's something else i'm supposed to be doing?

thanks

**Comment by mikebronner** [comment]
Hi @ITwrx, Laravel 6 is no longer supported. You are welcome to fork this repository and work out any issues in your fork.

**Comment by ITwrx** [comment]
that's disappointing. So, this package doesn't support Laravel LTS lifecycle? Or what's the package's policy on laravel support?
thanks

**Comment by ITwrx** [comment]
not that i expect it to be difficult to fix on my end, but many packages barely keep up with the LTS versions of laravel, while some packages only support the latest, so you end up forking everything just to keep an application working. If all packages at least supported currently supported Laravel LTS versions, there would be some common ground. Then, only people who needed the latest features would need to fork their needed packages.

**Comment by mikebronner** [comment]
Since this is still in pre-release, we will only support the most current version of Laravel. Once we go into 1.0 version, we might consider supporting LTS.
